(function(){
  'use strict';
  const appEl=document.getElementById('app');
  const state={screen:'home',game:null,theme:null,score:0,start:0,elapsed:0,timer:null,gameInstance:null,extra:'',saved:false,attractTimer:null,idleTimer:null,idleFinal:null};
  function header(){
    const top=UI.el('header','topbar');
    top.innerHTML=`<div class="topbar-inner"><div class="brand"><span class="brand-logo"><img src="assets/images/cdl-anapolis-colorido-branco.png" alt="CDL Anápolis"></span></div><div class="top-actions"><button class="icon-button sound-toggle" aria-label="${Sound.enabled?'Desativar':'Ativar'} som e música">${UI.svg(Sound.enabled?'speaker':'mute')}</button><button class="icon-button fullscreen-toggle" aria-label="Entrar em tela cheia">${UI.svg('fullscreen')}</button></div></div>`;
    top.querySelector('.sound-toggle').onclick=e=>{Sound.toggle();e.currentTarget.innerHTML=UI.svg(Sound.enabled?'speaker':'mute');e.currentTarget.setAttribute('aria-label',Sound.enabled?'Desativar som e música':'Ativar som e música');UI.toast(Sound.enabled?'Som e música ativados':'Som e música desativados')};
    top.querySelector('.fullscreen-toggle').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.().catch(()=>UI.toast('Tela cheia não disponível.'));else document.exitFullscreen?.()};
    return top;
  }
  function mount(screen){appEl.replaceChildren(header(),screen);screen.classList.add('screen-enter');resetIdle()}
  function screen(cls){const main=UI.el('main',`screen ${cls}`);main.id='main';return main}
  function gameIcon(game){const el=UI.el('span','game-icon');el.innerHTML=UI.svg(game.icon);return el}
  function showHome(){
    destroyGame();state.screen='home';state.game=state.theme=null;const main=screen('home-screen'),inner=UI.el('div','screen-inner hero'),copy=UI.el('section','hero-copy');copy.innerHTML='<div class="hero-kicker">Feira do Empreendedor</div><h1><span>Pense.</span><span>Jogue.</span><span>Empreenda.</span></h1><p>Escolha um desafio rápido, teste seus conhecimentos e conquiste seu lugar no placar.</p>';const grid=UI.el('section','game-grid');grid.setAttribute('aria-label','Escolha um jogo');GAME_DATA.games.forEach(game=>{const b=UI.el('button','game-card');b.style.setProperty('--game-color',game.color);b.append(gameIcon(game));const info=UI.el('span');info.append(UI.el('h2','',game.name),UI.el('p','',game.description));b.append(info);b.onclick=()=>{Sound.play('click');showThemes(game.id)};grid.append(b)});inner.append(copy,grid);main.append(inner);mount(main);clearTimeout(state.attractTimer);state.attractTimer=setTimeout(()=>{if(state.screen==='home'){main.classList.add('attract');UI.toast('Você consegue bater o recorde?')}},20000)
  }
  function showThemes(gameId){
    destroyGame();const game=UI.game(gameId);if(!game)return showHome();state.screen='themes';state.game=game;state.theme=null;const main=screen('theme-screen'),inner=UI.el('div','screen-inner');inner.style.setProperty('--game-color',game.color);const heading=UI.el('div','page-heading');heading.append(gameIcon(game));const title=UI.el('div');title.append(UI.el('h1','',game.name),UI.el('p','','Escolha um desafio'));heading.append(title);const grid=UI.el('div','theme-grid');GAME_DATA.themes.forEach((theme,i)=>{const b=UI.el('button','theme-card');b.style.setProperty('--game-color',game.color);b.append(UI.el('span','num',String(i+1).padStart(2,'0')),UI.el('span','theme-name',theme.name));b.onclick=()=>startGame(game.id,theme.id);grid.append(b)});const back=UI.el('button','secondary-button','Voltar ao início');back.style.marginTop='18px';back.onclick=showHome;inner.append(heading,grid,back);main.append(inner);mount(main)
  }
  function startGame(gameId,themeId){
    destroyGame();const game=UI.game(gameId),theme=UI.theme(themeId),engine=Games[gameId];if(!game||!theme||!engine){UI.toast('Não foi possível abrir este desafio.');return showHome()}state.screen='game';state.game=game;state.theme=theme;state.score=0;state.extra='';state.start=Date.now();state.elapsed=0;state.gameInstance=engine;const main=screen('game-screen');main.style.setProperty('--game-color',game.color);const hud=UI.el('div','game-hud'),back=UI.el('button','back-button');back.setAttribute('aria-label','Sair da partida');back.innerHTML=UI.svg('back');back.onclick=confirmExit;const title=UI.el('div','hud-title');title.append(UI.el('strong','',game.name),UI.el('span','',theme.name));const score=UI.el('div','stat');score.innerHTML='<span>Pontos</span><strong id="hud-score">0</strong>';const time=UI.el('div','stat');time.innerHTML='<span id="hud-extra">Tempo</span><strong id="hud-time">00:00</strong>';hud.append(back,title,score,time);const stage=UI.el('section','game-stage');stage.setAttribute('aria-label',`${game.name}: ${theme.name}`);main.append(hud,stage);mount(main);try{engine.init(stage,theme);state.timer=setInterval(updateTimer,1000)}catch(error){console.error(error);UI.modal({title:'Não foi possível iniciar',message:'O desafio encontrou um problema. Volte ao menu e tente novamente.',confirm:'Voltar ao menu',onConfirm:showHome})}
  }
  function updateTimer(){state.elapsed=Math.floor((Date.now()-state.start)/1000);const t=document.getElementById('hud-time');if(t)t.textContent=UI.time(state.elapsed)}
  function addScore(points,target){state.score+=points;const el=document.getElementById('hud-score');if(el)el.textContent=state.score.toLocaleString('pt-BR');UI.scorePop(points,target)}
  function setExtra(text){state.extra=text;const label=document.getElementById('hud-extra');if(label)label.textContent=text}
  function confirmExit(){UI.modal({title:'Encerrar partida?',message:'Seu progresso nesta rodada será perdido.',cancel:'Cancelar',confirm:'Sair',onConfirm:()=>showThemes(state.game.id)})}
  function destroyGame(){clearInterval(state.timer);state.timer=null;if(state.gameInstance?.destroy)try{state.gameInstance.destroy()}catch(e){console.warn(e)}state.gameInstance=null;clearTimeout(state.idleFinal);document.getElementById('modal-root').replaceChildren()}
  function finish(result){
    updateTimer();const speed=Math.max(0,600-state.elapsed*3),accuracy=result.total?result.correct/result.total:1;state.score+=500+speed+Math.round(accuracy*300);clearInterval(state.timer);state.timer=null;state.gameInstance?.destroy?.();state.gameInstance=null;state.screen='result';state.saved=false;Sound.play('complete');UI.confetti();showResult(result)
  }
  function showResult(result){
    const main=screen('result-screen'),card=UI.el('div','result-card');card.innerHTML='<h1>Rodada concluída!</h1>';card.append(UI.el('p','completed',`${state.game.name} · ${state.theme.name}`),UI.el('div','big-score',state.score.toLocaleString('pt-BR')));const stats=UI.el('div','result-stats');[['Tempo',UI.time(state.elapsed)],['Resultado',result.label||`${result.correct} / ${result.total}`]].forEach(([label,value])=>{const x=UI.el('div','stat');x.append(UI.el('span','',label),UI.el('strong','',value));stats.append(x)});const rankForm=UI.el('section','rank-form');rankForm.append(UI.el('h2','','Registre sua pontuação'),UI.el('p','completed','Digite seu nome no teclado abaixo.'));const display=UI.el('div','name-display','');display.setAttribute('aria-label','Nome do jogador');const keyboard=buildKeyboard(display,rankForm);rankForm.append(display,keyboard);const save=UI.el('button','primary-button','Salvar no ranking');save.onclick=()=>saveScore(display,rankForm,save);rankForm.append(save);const actions=UI.el('div','result-actions');actions.style.marginTop='18px';const again=UI.el('button','secondary-button','Jogar novamente'),other=UI.el('button','secondary-button','Outro desafio'),home=UI.el('button','secondary-button','Menu principal');again.onclick=()=>startGame(state.game.id,state.theme.id);other.onclick=()=>showThemes(state.game.id);home.onclick=showHome;actions.append(again,other,home);card.append(stats,rankForm,actions);main.append(card);mount(main)
  }
  function buildKeyboard(display){const keys='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').concat(['⌫','LIMPAR']);const board=UI.el('div','keyboard');keys.forEach(char=>{const b=UI.el('button',`key${char==='LIMPAR'?' wide':''}`,char);b.type='button';b.onclick=()=>{Sound.play('click');if(char==='⌫')display.textContent=display.textContent.slice(0,-1);else if(char==='LIMPAR')display.textContent='';else if(display.textContent.length<12)display.textContent+=char};board.append(b)});return board}
  function saveScore(display,container,button){if(state.saved)return;const name=display.textContent.trim();if(!name){UI.toast('Digite um nome para salvar.');return}Store.addScore({name,score:state.score,game:state.game.name,theme:state.theme.name});state.saved=true;button.disabled=true;button.textContent='Você entrou para o ranking!';renderRanking(container);Sound.play('correct')}
  function renderRanking(container){const old=container.querySelector('.ranking');if(old)old.remove();const ranking=UI.el('div','ranking');ranking.append(UI.el('h2','','Ranking local'));const rows=Store.ranking().slice(0,5);if(!rows.length)ranking.append(UI.el('p','empty-state','A primeira pontuação pode ser a sua.'));rows.forEach((row,i)=>{const r=UI.el('div','rank-row');r.append(UI.el('span','',`${i+1}º`),UI.el('span','',row.name),UI.el('span','',row.score.toLocaleString('pt-BR')));ranking.append(r)});container.append(ranking)}
  function resetIdle(){clearTimeout(state.idleTimer);clearTimeout(state.idleFinal);if(state.screen==='home'){clearTimeout(state.attractTimer);document.querySelector('.home-screen')?.classList.remove('attract');state.attractTimer=setTimeout(()=>{if(state.screen==='home')document.querySelector('.home-screen')?.classList.add('attract')},20000)}const limit=state.screen==='game'?120000:60000;state.idleTimer=setTimeout(onIdle,limit)}
  function onIdle(){if(state.screen==='game'){UI.modal({title:'Continuar jogando?',message:'A partida será encerrada em 15 segundos sem interação.',cancel:'Sair agora',confirm:'Continuar',onConfirm:resetIdle,onCancel:showHome});state.idleFinal=setTimeout(showHome,15000)}else if(state.screen!=='home')showHome()}
  window.App={showHome,showThemes,startGame,finish,addScore,setExtra,state};
  ['pointerdown','keydown'].forEach(type=>document.addEventListener(type,()=>{resetIdle();Sound.startMusic()},{passive:true}));
  window.addEventListener('error',e=>{console.error('Erro não tratado:',e.error||e.message)});
  showHome();
}());
