(function(){
  'use strict'; window.Games=window.Games||{};
  Games.association={
    init(stage,theme){this.stage=stage;this.pairs=UI.shuffle(theme.pairs).slice(0,6);this.selected=null;this.matched=0;this.errors=0;this.render()},destroy(){this.stage=null},
    render(){const wrap=UI.el('div','association-wrap'),left=UI.el('div','association-column'),right=UI.el('div','association-column');left.append(UI.el('h2','', 'Escolha um conceito'));right.append(UI.el('h2','', 'Encontre o significado'));this.pairs.forEach((pair,id)=>{const b=UI.el('button','choice-button',pair[0]);b.dataset.id=id;b.onclick=()=>this.pickLeft(b,id);left.append(b)});UI.shuffle(this.pairs.map((pair,id)=>({text:pair[1],id}))).forEach(x=>{const b=UI.el('button','choice-button',x.text);b.dataset.id=x.id;b.onclick=()=>this.pickRight(b,x.id);right.append(b)});wrap.append(left,right);this.stage.replaceChildren(wrap)},
    pickLeft(button,id){if(button.classList.contains('matched'))return;this.stage.querySelectorAll('.association-column:first-child .choice-button').forEach(b=>b.classList.remove('selected'));button.classList.add('selected');this.selected={button,id};Sound.play('click')},
    pickRight(button,id){if(!this.selected||button.classList.contains('matched')){UI.toast('Escolha primeiro um conceito à esquerda.');return}if(id===this.selected.id){button.classList.add('matched');this.selected.button.classList.remove('selected');this.selected.button.classList.add('matched');button.disabled=this.selected.button.disabled=true;this.matched++;App.addScore(110,button);Sound.play('correct');this.selected=null;if(this.matched===this.pairs.length)setTimeout(()=>App.finish({correct:this.matched,total:this.pairs.length,label:`${this.errors} erros`}),400)}else{this.errors++;button.classList.add('error');this.selected.button.classList.add('error');Sound.play('wrong');setTimeout(()=>{button.classList.remove('error');this.selected&&this.selected.button.classList.remove('error')},400)}}
  };
}());
